### ISSUE TITLE
Cluster ndmg data using NMF and K-means, Agglomerative, and MeanShift algorithms

### ISSUE THREAD

**Issue by alemmer1** [NeuroDataDesign/the-ents#18]
Goal: Run NMF on feature matrix produced from ndmg output to reduce dimensionality. Run various clustering algorithms including Kmeans, MeanShift, and Agglomerative Clustering with these features. Use various methods such as Silhouette Coefficient to choose the number of clusters.

DoD: 
• Reduce dimensionality of features for clustering with NMF 
• Run Kmeans, Meanshift, and Agglomerative clustering algorithms using features from NMF

**Comment by alemmer1** [comment]
Input: _n_ edgelists 
Output: _k_ clusters
    (1) Read in _n_ edgelists from HBN as matrices 
    (2) For each edgelist 
        a. Run NMF with 3 components (using sklearn) 
            i. Output: 3 x 3 array 
        b. Turn 3 x 3 array into 1 x 9 array 
    (3) Combine _n_ 1 x 9 arrays into a n x 9 matrix 
    (4) With the _n_ x 9 matrix and _k_ as input 
        a. Run kmeans clustering (using sklearn) 
        b. Run MeanShift clustering (using sklearn) 
        c. Run Agglomerative Clustering (using sklearn) 
    (5) Plot clusters in multiple dimensions. Repeat step 4 with a different _k_ until the clusters are 
          visually sound.

**Comment by jovo** [comment]
"cluster ndmg data using NMF o {kmeans, etc}"
would be a sufficient title.

also, "Port U-RerF to Python" is a totally separate task, so it goes seperately.  
also, that is too ambitious, there is too much there.
also, how will you choose the number of dimensions and the number of clusters?

**Comment by jovo** [comment]
- prove silloutte distance does or doesn't care about number of dimensions by hand.
